version: '3.7'
services:
    postgres13:
        image: postgres:13
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=Password3000!!
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5433:5432'
        volumes: 
          - ./data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql