version: "3.7"

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "8000:80"
      - "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./site:/srv