version: '3.7'

networks:
  shared-network:
    external: true

services:
  postgres_pgvector:
    shm_size: "2gb"
    image: postgres-pgvector
    restart: "no"
    networks:
      - shared-network
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password3000!!
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5434:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./shared:/mnt
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sq