server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /mnt/promtail/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
target_config:
  sync_period: 10s
scrape_configs:
- job_name: system
  # decompression:
  #   enabled: true
  #   initial_sleep: 10s
  #   format: gz
  static_configs:
  - targets:
      - loki
    labels:
      job: varlogs
      __path__: /var/log/*.log
