version: "3"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD_HERE
    ports:
      - 3306:3306
    volumes:
      # to allow imports from local fs
      - ./shared:/var/lib/mysql
