version: '3.7'
services:
  postgres13_age:
    image: apache/age:PG13_latest
    restart: always
    # see networks section below
    networks:
      - postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password3000!!
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5532:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
networks:
  postgresql:
    # use externaly created network for postgresql
    # this can be commented out if not needed but it is useful to have a network for other dockers communicating with this PostgreSQL
    external: true
